### ISSUE TITLE
Why two DHCPd's?  dnsmasq and isc-dhcp-server 

### ISSUE THREAD

**Issue by bugre** [inovex/fluffy-unicorn#3]
Hi,
I'm studying your solution for baremetal coreos deployment, and got curious why you choose two dhcpd servers/services?
- dnsmasq 
- isc-dhcp

I've read the presentation slides and also gone thought the provision scripts, but i'm missing the knowledge to understand the whole picture so i'm sure that i'm missing some clue to get why the two are needed.

Cloud it all be done by dnsmasq?

Thank you in advance for your time.
Have a nice day.

**Comment by johscheuer** [comment]
Probably this could also be possible with dnsmasq only (even I didn't tried it).

**Comment by bugre** [comment]
thanks! 
Closing to cleanup
